const jerseyOrdersData = [
  // CATEGORY: ANAK-ANAK
  {
    id: 1,
    category: "Anak-Anak",
    name: "ZAIN",
    number: "27",
    size: "S",
    notes: "ANAK-ANAK",
    customer: "FATHUL",
    price: 120000,
    paid: 120000,
    paymentStatus: "LUNAS",
    paymentDate: "31/05/2026"
  },
  {
    id: 2,
    category: "Anak-Anak",
    name: "ZAID",
    number: "07",
    size: "S",
    notes: "ANAK-ANAK",
    customer: "FATHUL",
    price: 120000,
    paid: 120000,
    paymentStatus: "LUNAS",
    paymentDate: "31/05/2026"
  },
  {
    id: 3,
    category: "Anak-Anak",
    name: "GHAZI",
    number: "10",
    size: "M",
    notes: "ANAK-ANAK",
    customer: "HABIB",
    price: 120000,
    paid: 120000,
    paymentStatus: "LUNAS",
    paymentDate: "31/05/2026"
  },
  {
    id: 4,
    category: "Anak-Anak",
    name: "EMIR",
    number: "3",
    size: "3-4 TAHUN",
    notes: "ANAK-ANAK",
    customer: "HABIB",
    price: 120000,
    paid: 120000,
    paymentStatus: "LUNAS",
    paymentDate: "31/05/2026"
  },
  {
    id: 5,
    category: "Anak-Anak",
    name: "HAFA",
    number: "19",
    size: "2 TAHUN",
    notes: "ANAK-ANAK",
    customer: "AZMI",
    price: 120000,
    paid: 120000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 6,
    category: "Anak-Anak",
    name: "FAIZ",
    number: "17",
    size: "S",
    notes: "ANAK-ANAK",
    customer: "EDI",
    price: 120000,
    paid: 120000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 7,
    category: "Anak-Anak",
    name: "FAQIH",
    number: "7",
    size: "5 TAHUN",
    notes: "ANAK-ANAK",
    customer: "EDI",
    price: 120000,
    paid: 120000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 8,
    category: "Anak-Anak",
    name: "BADZLA",
    number: "8",
    size: "L",
    notes: "ANAK-ANAK",
    customer: "SOFIYAN",
    price: 120000,
    paid: 120000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 9,
    category: "Anak-Anak",
    name: "RAZAN",
    number: "10",
    size: "5 TAHUN",
    notes: "ANAK-ANAK",
    customer: "RAMADHAN",
    price: 120000,
    paid: 120000,
    paymentStatus: "LUNAS",
    paymentDate: "2/6/2026"
  },
  {
    id: 10,
    category: "Anak-Anak",
    name: "AZ•KA",
    number: "19",
    size: "L",
    notes: "ANAK-ANAK",
    customer: "HADI",
    price: 120000,
    paid: 120000,
    paymentStatus: "LUNAS",
    paymentDate: "2/6/2026"
  },
  {
    id: 11,
    category: "Anak-Anak",
    name: "RAFKA",
    number: "67",
    size: "M",
    notes: "ANAK-ANAK",
    customer: "HADI",
    price: 120000,
    paid: 120000,
    paymentStatus: "LUNAS",
    paymentDate: "2/6/2026"
  },
  {
    id: 12,
    category: "Anak-Anak",
    name: "SYAUKA",
    number: "03",
    size: "3-4 TAHUN",
    notes: "ANAK-ANAK",
    customer: "HADI",
    price: 120000,
    paid: 120000,
    paymentStatus: "LUNAS",
    paymentDate: "2/6/2026"
  },

  // CATEGORY: DEWASA / UMUM
  {
    id: 13,
    category: "Dewasa / Umum",
    name: "AZMI",
    number: "18",
    size: "XXL",
    notes: "",
    customer: "AZMI",
    price: 135000,
    paid: 90000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 14,
    category: "Dewasa / Umum",
    name: "HABIB",
    number: "2",
    size: "L",
    notes: "",
    customer: "HABIB",
    price: 135000,
    paid: 85000,
    paymentStatus: "LUNAS",
    paymentDate: "31/05/2026"
  },
  {
    id: 15,
    category: "Dewasa / Umum",
    name: "RAMA",
    number: "8",
    size: "XXL",
    notes: "",
    customer: "RAMADHAN",
    price: 135000,
    paid: 90000,
    paymentStatus: "LUNAS",
    paymentDate: "2/6/2026"
  },
  {
    id: 16,
    category: "Dewasa / Umum",
    name: "OZIL",
    number: "23",
    size: "L",
    notes: "",
    customer: "RONAL",
    price: 130000,
    paid: 85000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 17,
    category: "Dewasa / Umum",
    name: "ABI FAFA",
    number: "19",
    size: "L",
    notes: "",
    customer: "EDI",
    price: 130000,
    paid: 85000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 18,
    category: "Dewasa / Umum",
    name: "APU",
    number: "28",
    size: "XXXXXXL",
    notes: "(L: 62cm P: 78cm bawahan XXXXL)",
    customer: "DARMA",
    price: 150000,
    paid: 105000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 19,
    category: "Dewasa / Umum",
    name: "DEANDLESS",
    number: "7",
    size: "L",
    notes: "",
    customer: "DEDEN",
    price: 130000,
    paid: 85000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 20,
    category: "Dewasa / Umum",
    name: "SUHAR",
    number: "15",
    size: "XXL",
    notes: "",
    customer: "SUHARSONO",
    price: 135000,
    paid: 90000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 21,
    category: "Dewasa / Umum",
    name: "WEGA",
    number: "26",
    size: "L",
    notes: "",
    customer: "EGA",
    price: 130000,
    paid: 85000,
    paymentStatus: "LUNAS",
    paymentDate: "31/05/2026"
  },
  {
    id: 22,
    category: "Dewasa / Umum",
    name: "FITRA",
    number: "10",
    size: "XXL",
    notes: "",
    customer: "FITRA",
    price: 135000,
    paid: 90000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 23,
    category: "Dewasa / Umum",
    name: "TAUFIQ",
    number: "44",
    size: "XXL",
    notes: "LENGAN PANJANG",
    customer: "TAUFIQ",
    price: 145000,
    paid: 100000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 24,
    category: "Dewasa / Umum",
    name: "AFRIZAL",
    number: "12",
    size: "XXL",
    notes: "",
    customer: "AFRIZAL",
    price: 135000,
    paid: 90000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 25,
    category: "Dewasa / Umum",
    name: "R. ARDONA",
    number: "13",
    size: "XXXL",
    notes: "",
    customer: "RIYAN",
    price: 140000,
    paid: 95000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 26,
    category: "Dewasa / Umum",
    name: "ANGGIAN",
    number: "20",
    size: "XXL",
    notes: "",
    customer: "GILANG",
    price: 135000,
    paid: 90000,
    paymentStatus: "LUNAS",
    paymentDate: "2/6/2026"
  },
  {
    id: 27,
    category: "Dewasa / Umum",
    name: "AN NASR",
    number: "3",
    size: "L",
    notes: "",
    customer: "NASRUDIN",
    price: 130000,
    paid: 85000,
    paymentStatus: "LUNAS",
    paymentDate: "1/6/2026"
  },
  {
    id: 28,
    category: "Dewasa / Umum",
    name: "WIDI",
    number: "9",
    size: "XL",
    notes: "",
    customer: "WIDI",
    price: 130000,
    paid: 85000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 29,
    category: "Dewasa / Umum",
    name: "HABIB",
    number: "12",
    size: "XXL",
    notes: "",
    customer: "HABIB UAM",
    price: 135000,
    paid: 90000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 30,
    category: "Dewasa / Umum",
    name: "TSAQIF",
    number: "21",
    size: "XL",
    notes: "",
    customer: "KAHFI",
    price: 130000,
    paid: 130000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 31,
    category: "Dewasa / Umum",
    name: "ENJU",
    number: "14",
    size: "XL",
    notes: "",
    customer: "ENDRI",
    price: 130000,
    paid: 85000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 32,
    category: "Dewasa / Umum",
    name: "HENDRA",
    number: "55",
    size: "L",
    notes: "",
    customer: "HENDRA",
    price: 130000,
    paid: 85000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 33,
    category: "Dewasa / Umum",
    name: "BOB",
    number: "11",
    size: "XL",
    notes: "",
    customer: "NANANG",
    price: 130000,
    paid: 85000,
    paymentStatus: "LUNAS (+45000)",
    paymentDate: "1/6/2026"
  },
  {
    id: 34,
    category: "Dewasa / Umum",
    name: "DIE'Z",
    number: "77",
    size: "L",
    notes: "",
    customer: "SALDI",
    price: 130000,
    paid: 85000,
    paymentStatus: "LUNAS (CASH)",
    paymentDate: "2/6/2026"
  },
  {
    id: 35,
    category: "Dewasa / Umum",
    name: "ARIF HADI",
    number: "27",
    size: "XXL",
    notes: "",
    customer: "ARIF BJ",
    price: 135000,
    paid: 135000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 36,
    category: "Dewasa / Umum",
    name: "AGIL",
    number: "99",
    size: "M",
    notes: "",
    customer: "AGIL",
    price: 130000,
    paid: 85000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 37,
    category: "Dewasa / Umum",
    name: "FATHUR",
    number: "00",
    size: "L",
    notes: "",
    customer: "FATHUR",
    price: 130000,
    paid: 85000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 38,
    category: "Dewasa / Umum",
    name: "MU'AFA",
    number: "88",
    size: "XL",
    notes: "",
    customer: "PUNGKI",
    price: 130000,
    paid: 85000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 39,
    category: "Dewasa / Umum",
    name: "HADI",
    number: "31",
    size: "XXXL",
    notes: "ATASAN",
    customer: "HADI",
    price: 100000,
    paid: 100000,
    paymentStatus: "LUNAS",
    paymentDate: "2/6/2026"
  },
  {
    id: 40,
    category: "Dewasa / Umum",
    name: "ANAS",
    number: "14",
    size: "L",
    notes: "",
    customer: "ANAS",
    price: 130000,
    paid: 85000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 41,
    category: "Dewasa / Umum",
    name: "BIEBIE",
    number: "5",
    size: "XXXL",
    notes: "",
    customer: "HABIBI",
    price: 140000,
    paid: 95000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 42,
    category: "Dewasa / Umum",
    name: "MARIOSETA",
    number: "58",
    size: "XL",
    notes: "",
    customer: "ARSETA",
    price: 130000,
    paid: 130000,
    paymentStatus: "LUNAS",
    paymentDate: "31/05/2026"
  },
  {
    id: 43,
    category: "Dewasa / Umum",
    name: "VAN SHASYA",
    number: "90",
    size: "XL",
    notes: "",
    customer: "ROLI",
    price: 130000,
    paid: 130000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 44,
    category: "Dewasa / Umum",
    name: "AGENG",
    number: "6",
    size: "M",
    notes: "",
    customer: "AGENG",
    price: 130000,
    paid: 85000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 45,
    category: "Dewasa / Umum",
    name: "AHY",
    number: "1",
    size: "XXL",
    notes: "KIPER BIRU",
    customer: "ANDRE",
    price: 135000,
    paid: 90000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 46,
    category: "Dewasa / Umum",
    name: "EZIO",
    number: "25",
    size: "XXL",
    notes: "KIPER HITAM",
    customer: "FADHIL",
    price: 135000,
    paid: 90000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 47,
    category: "Dewasa / Umum",
    name: "QORI",
    number: "24",
    size: "XXXL",
    notes: "",
    customer: "QORI",
    price: 140000,
    paid: 140000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 48,
    category: "Dewasa / Umum",
    name: "ADIET",
    number: "27",
    size: "XL",
    notes: "",
    customer: "ADIET UAM",
    price: 130000,
    paid: 130000,
    paymentStatus: "LUNAS",
    paymentDate: "31/05/2026"
  },
  {
    id: 49,
    category: "Dewasa / Umum",
    name: "RIZKY",
    number: "95",
    size: "XL",
    notes: "",
    customer: "RIZKY",
    price: 130000,
    paid: 85000,
    paymentStatus: "LUNAS",
    paymentDate: "1/6/2026"
  },
  {
    id: 50,
    category: "Dewasa / Umum",
    name: "SOFIYAN",
    number: "41",
    size: "L",
    notes: "",
    customer: "SOFIYAN",
    price: 130000,
    paid: 130000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 51,
    category: "Dewasa / Umum",
    name: "D A N I'",
    number: "24",
    size: "L",
    notes: "",
    customer: "DANI UAM",
    price: 130000,
    paid: 130000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 52,
    category: "Dewasa / Umum",
    name: "NDEN",
    number: "76",
    size: "XL",
    notes: "",
    customer: "DWI",
    price: 130000,
    paid: 85000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 53,
    category: "Dewasa / Umum",
    name: "EDDY",
    number: "22",
    size: "L",
    notes: "KIPER HITAM",
    customer: "EDDY KUR",
    price: 130000,
    paid: 85000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 54,
    category: "Dewasa / Umum",
    name: "TYO",
    number: "42",
    size: "XXL",
    notes: "KIPER HITAM",
    customer: "TYO UAM",
    price: 135000,
    paid: 135000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 55,
    category: "Dewasa / Umum",
    name: "FEBIAN",
    number: "4",
    size: "XL",
    notes: "",
    customer: "FEBI",
    price: 130000,
    paid: 130000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 56,
    category: "Dewasa / Umum",
    name: "ZHANG LINGHE",
    number: "01",
    size: "XXL",
    notes: "KIPER HITAM",
    customer: "FIKA",
    price: 135000,
    paid: 135000,
    paymentStatus: "LUNAS",
    paymentDate: "31/05/2026"
  },
  {
    id: 57,
    category: "Dewasa / Umum",
    name: "REHAN",
    number: "20",
    size: "XL",
    notes: "KIPER HITAM",
    customer: "REHAN",
    price: 130000,
    paid: 130000,
    paymentStatus: "",
    paymentDate: ""
  },
  {
    id: 58,
    category: "Dewasa / Umum",
    name: "CHEN ZHEYUAN",
    number: "01",
    size: "XXL",
    notes: "KIPER BIRU - ATASAN",
    customer: "FIKA",
    price: 95000,
    paid: 95000,
    paymentStatus: "LUNAS",
    paymentDate: "31/05/2026"
  }
];
